name: Railway Stack Workflow Deployment
on:
  push:
    branches:
      - 'release/v\d+\.\d+'


jobs:
 deploy_railway:
  runs-on: ubuntu-latest

  steps:

  - name: checkout your source 
    uses: actions/checkout@v3

  - name: Build Go binary 
    run: go build -o app

  - name: Build and deploy to Railway 
    uses: bervProject/railway-deploy@main
    env:
      RAILWAY_TOKEN: ${{ secrets.TOKEN_RAILWAY_PROJECT }} 
      INSTANCE_NAME: ${{ secrets.INSTANCE_VARIABLE }}
    with:
      service: "plucky-earthquake" 
    

  - name: Notify Slack
    uses: 8398a7/action-slack@v3
    with:
    status: ${{ job.status }}
    blocks: |
      [
        {
          "type": "section",
          "text": {
            "type": "mrkdwn",
            "text": "*Name:* XU CONG\n*Matriculation Number:* 123\n*Email:* 123@sg\n*Repository:* ${{ github.repository }}\n*Deployment URL:* ${{ secrets.RAILWAY_APP_URL }}"
          }
        },
        {
          "type": "actions",
          "elements": [
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "text": "Go"
              },
              "url": "${{ secrets.RAILWAY_APP_URL }}"
            }
          ]
        }
      ]
  env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST_WEBHOOK_URL }}
 
      
    


