name: Railway Stack Workflow Deployment
on:
  push:
    branches:
      - 'release/v\d+\.\d+'


jobs:
 deploy_railway_slack:
  runs-on: ubuntu-latest
  
  steps:

  - name: Print RAILWAY_APP_URL_VAR variable
    run: echo ${{ vars.RAILWAY_APP_URL_VAR }}

  - name: checkout  
    uses: actions/checkout@v3

  - name: Build Go 
    run: go build -o app

  - name: Build and deploy to Railway 
    uses: bervProject/railway-deploy@main
    env:
      RAILWAY_TOKEN: ${{ secrets.TOKEN_RAILWAY_PROJECT }} 
      INSTANCE_NAME: ${{ secrets.INSTANCE_VARIABLE }}
    with:
      service: "plucky-earthquake" 

  - name: Send custom JSON data to Slack
    id: slack
    uses: slackapi/slack-github-action@v1.23.0
    with:
      payload: |
        {
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Name:* ${{ vars.INSTANCE_VARIABLE_VAR }}\n*Matriculation Number:* 123\n*Email:* 123@sg\n*Repository:* ${{ github.repository }}\n*Deployment URL:* ${{ vars.RAILWAY_APP_URL_VAR }}"
              }
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "${{ vars.RAILWAY_APP_URL_VAR }}"
              },
              "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Go"
                },
                "url": "${{ vars.RAILWAY_APP_URL_VAR }}"
              }
            }
          ]
        }
    env:
      SLACK_WEBHOOK_URL: "${{ vars.SLACK_TEST_WEBHOOK_URL_VAR }}"

 
      
    


