name: Railway Stack Workflow Deployment
on:
  push:
    branches:
      - 'release/v\d+\.\d+'


jobs:
 deploy_railway_slack:
  runs-on: ubuntu-latest
  
  steps:

  - name: Print RAILWAY_APP_URL_VAR variable
    run: echo ${{ vars.INSTANCE_VARIABLE_VAR }}

  - name: checkout  
    uses: actions/checkout@v3

  - name: Build Go 
    run: go build -o app

  - name: Build and deploy to Railway 
    uses: bervProject/railway-deploy@main
    env:
      RAILWAY_TOKEN: ${{ secrets.TOKEN_RAILWAY_PROJECT }} 
      INSTANCE_NAME: ${{ secrets.INSTANCE_VARIABLE }}
    with:
      service: "plucky-earthquake" 

  - name: Send custom JSON data to Slack
    id: slack
    uses: slackapi/slack-github-action@v1.23.0
    with:
      payload: |
        {
          "text": "",
          "blocks": [
            {
              "type": "header",
              "text": {
                "type": "plain_text",
                "text": "test header"
              }
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Name:*test"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Email:*\n<example.com|Fred Enriquez>"
                }
              ]
            },
            {
              "type": "section",
              "fields": [
                {
                  "type": "mrkdwn",
                  "text": "*Matriculation:*test"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Repository:*\n<example.com|Fred Enriquez>"
                }
              ]
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "${{ vars.RAILWAY_APP_URL_VAR }}"
              },
              "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Go"
                },
                "url": "${{ vars.RAILWAY_APP_URL_VAR }}"
              }
            }
          ]
        }
    env: 
      SLACK_WEBHOOK_URL: "${{ vars.SLACK_TEST_WEBHOOK_URL_VAR }}"

 
      
    


